### ISSUE TITLE
pod install

### ISSUE THREAD

**Issue by zx0922** [hustlzp/xichuangzhu-ios#62]
pod install总完成不了是怎么回事啊

Updating local specs repositories

CocoaPods 1.0.0.beta.8 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using AVOSCloud (3.1.6.8)
Using Crashlytics (3.4.1)
Using FMDB (2.6)
Using Fabric (1.6.1)
Installing HTCopyableLabel (0.0.7)
Installing LeanCloudFeedback (0.0.8)
Installing MBProgressHUD (0.9.1)
Installing Masonry (0.6.3)
Installing SDWebImage (3.7.3)
Installing UITableView+FDTemplateLayoutCell (1.4.beta)

[!] Error installing UITableView+FDTemplateLayoutCell
[!] /usr/bin/git clone https://github.com/forkingdog/UITableView-FDTemplateLayoutCell.git /var/folders/3y/nm8jxwk9321gwcv_z6__mwcr0000gn/T/d20160419-15512-mo8wp9 --single-branch --depth 1 --branch 1.4.beta

Cloning into '/var/folders/3y/nm8jxwk9321gwcv_z6__mwcr0000gn/T/d20160419-15512-mo8wp9'...
fatal: unable to access 'https://github.com/forkingdog/UITableView-FDTemplateLayoutCell.git/': Failed to connect to github.com port 443: Operation timed out

**Comment by hustlzp** [comment]
connect to github.com port 443: Operation timed out
 网络问题

多次运行，直至成功...

```
pod install --no-repo-update
```

**Comment by zzgo** [comment]
我建议你换个镜像，或者像作者给的方式一样不更新repo直接装
