### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by wanminny** [hustlzp/xichuangzhu-ios#63]
初步看了下貌似你这个数据库都是本地的；而且也没有用到会话；除了一个FEED组件以外，貌似与LeanCloud木有关系哦。其他貌似都是本地数据；除了友盟，统计等以外基本无网络交互哦~~大神指点。

**Comment by hustlzp** [comment]
是的，单机版...

**Comment by hustlzp** [comment]
我做这个App的时候还不太会和服务器通信。

以后会做的。

**Comment by wanminny** [comment]
还是不错的；有开源的网络交互作品否，呵呵，原生的；

**Comment by hustlzp** [comment]
有一个，是目前的创业项目，所以开源不了。。。不好意思
